name: test

on:
  push:
    branches:
      - dev

jobs:
  create_new_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: 'dev'
          destination_branch: 'main'
          pr_title: "title"
          pr_body: "body"
          labels: release
